name: paper_score_estimation
channels:
  - pytorch-lts
  - nvidia
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - ca-certificates=2022.07.19
  - certifi=2022.6.15
  - cudatoolkit=11.1.74
  - intel-openmp=2021.4.0
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuv=1.40.0
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numpy=1.22.3
  - numpy-base=1.22.3
  - openssl=1.1.1q
  - pip=22.1.2
  - python=3.9.12
  - pytorch=1.8.2
  - readline=8.1.2
  - setuptools=61.2.0
  - six=1.16.0
  - sqlite=3.38.5
  - tk=8.6.12
  - typing_extensions=4.1.1
  - tzdata=2022a
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - pip:
    - absl-py==1.2.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - alembic==1.4.1
    - antlr4-python3-runtime==4.8
    - anyio==3.6.1
    - appdirs==1.4.4
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - arxiv==1.4.2
    - asttokens==2.0.5
    - async-timeout==4.0.2
    - attrs==22.1.0
    - babel==2.10.3
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - black==21.5b1
    - bleach==5.0.1
    - cachetools==5.2.0
    - captum==0.5.0
    - cffi==1.15.1
    - charset-normalizer==2.1.0
    - classopt==0.1.7
    - click==8.1.3
    - cloudpickle==2.1.0
    - colorama==0.4.5
    - commonmark==0.9.1
    - cycler==0.11.0
    - databricks-cli==0.17.0
    - debugpy==1.6.2
    - decorator==5.1.1
    - defusedxml==0.7.1
    - docker==5.0.3
    - entrypoints==0.4
    - executing==0.9.1
    - fastjsonschema==2.16.1
    - feedparser==6.0.10
    - filelock==3.7.1
    - flask==2.1.3
    - frozenlist==1.3.0
    - fsspec==2022.7.1
    - future==0.18.2
    - gitdb==4.0.9
    - gitpython==3.1.27
    - google-auth==2.9.1
    - google-auth-oauthlib==0.4.6
    - greenlet==1.1.2
    - grpcio==1.48.0
    - gunicorn==20.1.0
    - huggingface-hub==0.8.1
    - hydra-core==1.0.6
    - idna==3.3
    - importlib-metadata==4.12.0
    - ipykernel==6.15.1
    - ipython==8.4.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.5
    - itsdangerous==2.1.2
    - jedi==0.18.1
    - jinja2==3.1.2
    - joblib==1.1.0
    - json5==0.9.8
    - jsonschema==4.8.0
    - jupyter-client==7.3.4
    - jupyter-core==4.11.1
    - jupyter-server==1.18.1
    - jupyterlab==3.0.16
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.15.0
    - jupyterlab-widgets==1.1.1
    - kiwisolver==1.4.4
    - mako==1.2.1
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.4.2
    - matplotlib-inline==0.1.3
    - mistune==0.8.4
    - mlflow==1.17.0
    - multidict==6.0.2
    - mypy-extensions==0.4.3
    - nbclassic==0.4.3
    - nbclient==0.6.6
    - nbconvert==6.5.0
    - nbformat==5.4.0
    - nest-asyncio==1.5.5
    - notebook==6.4.12
    - notebook-shim==0.1.0
    - oauthlib==3.2.0
    - omegaconf==2.0.6
    - packaging==21.3
    - pandas==1.2.4
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pathspec==0.9.0
    - pdf2image==1.16.0
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.2.0
    - pprintpp==0.4.0
    - prometheus-client==0.14.1
    - prometheus-flask-exporter==0.20.2
    - prompt-toolkit==3.0.30
    - protobuf==3.19.4
    - psutil==5.9.1
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.21
    - pydeprecate==0.3.2
    - pygments==2.12.0
    - pyjwt==2.4.0
    - pyparsing==3.0.9
    - pyrsistent==0.18.1
    - pytesseract==0.3.9
    - python-dateutil==2.8.2
    - python-editor==1.0.4
    - pytorch-lightning==1.6.5
    - pytz==2022.1
    - pyyaml==5.4.1
    - pyzmq==23.2.0
    - querystring-parser==1.2.4
    - regex==2022.7.25
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - rich==10.2.2
    - rsa==4.9
    - sacremoses==0.0.53
    - scikit-learn==0.24.2
    - scipy==1.8.1
    - seaborn==0.11.1
    - semanticscholar==0.1.6
    - send2trash==1.8.0
    - sgmllib3k==1.0.0
    - smmap==5.0.0
    - sniffio==1.2.0
    - soupsieve==2.3.2.post1
    - sqlalchemy==1.4.39
    - sqlparse==0.4.2
    - stack-data==0.3.0
    - tabulate==0.8.10
    - tenacity==8.0.1
    - tensorboard==2.9.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - terminado==0.15.0
    - threadpoolctl==3.1.0
    - tinycss2==1.1.1
    - tokenizers==0.12.1
    - toml==0.10.2
    - torchmetrics==0.6.0
    - tornado==6.2
    - tqdm==4.60.0
    - traitlets==5.3.0
    - transformers==4.21.0
    - urllib3==1.26.11
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.3.3
    - werkzeug==2.2.1
    - widgetsnbextension==3.5.2
    - wordcloud==1.8.1
    - yarl==1.7.2
    - zipp==3.8.1
